[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ixel"
version = "0.1.0"
authors = [
  { name="Author Name", email="author@example.com" },
]
description = "A reinforcement learning system for database indexing."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "torch>=2.1.0",
    "sqlglot>=20.11.0",
]

[project.optional-dependencies]
test = [
    "pytest==8.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]
